//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KittyPizza.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaPriceLookupTable
    {
        public int Id { get; set; }
        public decimal SmallSizeCost { get; set; }
        public decimal MediumSizeCost { get; set; }
        public decimal LargeSizeCost { get; set; }
        public decimal ThickCrustCost { get; set; }
        public decimal ThinCrustCost { get; set; }
        public decimal RegularCrustCost { get; set; }
        public decimal MouseCost { get; set; }
        public decimal GoldfishCost { get; set; }
        public decimal CatnipCost { get; set; }
        public decimal GrassCost { get; set; }
    }
}
