//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KittyPizza.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid OrderId { get; set; }
        public KittyPizza.DTO.Enums.SizeType Size { get; set; }
        public KittyPizza.DTO.Enums.CrustType Crust { get; set; }
        public bool Mouse { get; set; }
        public bool Goldfish { get; set; }
        public bool Catnip { get; set; }
        public bool Grass { get; set; }
        public decimal TotalCost { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public KittyPizza.DTO.Enums.PaymentType PaymentType { get; set; }
        public bool Completed { get; set; }
    }
}
